package(default_visibility = ["//hermes:__subpackages__"])

py_library(
    name = "pyspark_transformer",
    srcs = glob(["*.py"]),
    imports = ["."],
    deps = [
        "//frameworks/python:lib",
        "//hermes/tools/py/logging",
        "//hermes/tools/py/utils",
    ],
)
