package(default_visibility = ["//hermes:__subpackages__"])

py_library(
    name = "sklearn_piepline_utils",
    srcs = glob(["*.py"]),
    imports = ["."],
    deps = [
        "//frameworks/python:lib",
        "//hermes/tools/py/grpc_server",
        "//hermes/tools/py/logging",
        "//hermes/tools/py/utils",
    ],
)
